services:
  backend:
    build: ./TasksManagementBackend
    container_name: tasks-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./TasksManagementFrontend
    container_name: tasks-frontend
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    restart: always
